spring:
  application:
    name: weatherApp

app:
  version: '@project.version@'

location-forecast:
  base-url: https://api.met.no/weatherapi/locationforecast/2.0
  user-agent: ${spring.application.name}/${app.version} github.com/BredeFK/weatherApp

nominatim:
  base-url: https://nominatim.openstreetmap.org

strava:
  base-url: https://www.strava.com/api/v3
  client-id: ${STRAVA_CLIENT_ID}
  client-secret: ${STRAVA_CLIENT_SECRET}
  refresh-token: ${STRAVA_REFRESH_TOKEN}