spring:
  application:
    name: weatherApp

app:
  version: '@project.version@'

location-forecast:
  base-url: https://api.met.no/weatherapi/locationforecast/2.0
  user-agent: ${spring.application.name}/${app.version} github.com/BredeFK/weatherApp